# Generated by Django 4.0.2 on 2022-04-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sonubhaiapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('State', models.CharField(max_length=200)),
                ('Places', models.CharField(max_length=200)),
                ('Date', models.CharField(max_length=200)),
            ],
        ),
    ]
