# Generated by Django 4.0.2 on 2022-05-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sonubhaiapp', '0004_bookin_delete_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='booket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Phone', models.CharField(max_length=200)),
                ('Email', models.CharField(max_length=200)),
                ('Today', models.CharField(max_length=200)),
                ('State', models.CharField(max_length=200)),
                ('Places', models.CharField(max_length=200)),
                ('Date', models.CharField(max_length=200)),
                ('Enddate', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
