# Generated by Django 4.0.2 on 2022-05-14 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sonubhaiapp', '0005_booket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booket',
            name='Date',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='booket',
            name='Email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='booket',
            name='Name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='booket',
            name='Phone',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='booket',
            name='Places',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='booket',
            name='State',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='booket',
            name='Today',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
